### ISSUE TITLE
Looking to get more exposure for "in-cluster" debugging with Istio

### ISSUE THREAD

**Issue by davidmichaelkarr** [askmeegs/istiobyexample#4]
Ok, well, this is going to seem odd, writing an issue for this, but I can't figure out any other way to get a message to you (I did tweet your handle, but perhaps no one pays attention to that).

I watched the recording of your Istio presentation at O'Reilly SACon.  Good presentation.  Not long enough. :) You talked about DevOps and velocity and "accelerating the devops feedback loop".  I wanted to mention an idea that I saw the potential for as soon as I read about the VirtualService many months ago, but I've only heard this idea mentioned elsewhere perhaps once or twice in some obscure presentations.

We've been using k8s for a while, but we haven't quite made the jump to Istio, despite the fact we've been researching it for quite a while.

I believe our main application architecture is probably similar to many others, with a front-end gui that distributes requests to "front-end" microservices, and then disseminates requests to lower-level services, and back-end systems of record.

Developers change the system by creating a pull request, which gets compiled and goes through several quality gates, and then the PR gets reviewed and approved and then merged to a target branch (master or release branch), which then spawns a big target build, which does most of what the PR build does, with additional steps.  This whole process can be frustratingly long, and that's just for deploys to the dev cluster. If they're working on something in the "test" cluster, the pipeline has to go through the dev cluster first.  It's painful, but it helps to add some assurance of quality.

If the developer goes through all of that, and they test the system and it doesn't work quite right, the only information they have to look at is metrics, logs, and what they see on the screen. Extremely often, developers will submit pull requests with only new logging calls, because that's all they can do to get more information out of it.

Thirty years ago I worked on an embedded system that didn't provide any way to debug the code in the system.  Thirty years later we still have the same limitations.

What I want to see happen is for the developer to look at a line in their source code in their editor, press a key to set a breakpoint on the line, then go to the front-end for the application, click a button, and have the breakpoint be hit in the editor.  If developers can do that, they can add velocity to their feedback loop (some of the points you were talking about in your presentation).

We can sort of do this today.  Our code is Java, which allows for a remote debugger (Eclipse, for instance) to connect to a process and step through the code.  Other languages likely have similar capabilities.  I could expose the debugger port in the container, use a "port-forward" from my desktop to map that port to a local port, and then connect to that port from my debugger.  I could then go to the GUI, click the button, and it will hit my breakpoint.  The problem is, there are dozens of other people using the same cluster, perhaps going through similar test cases, so this will suddenly overload my debugger with dozens of requests, all hitting my breakpoint.  Epic fail.

When I first read about using header routing with the Istio VirtualService, I realized we were close to achieving this goal.

The basic structure of this solution is this:

The developer goes to the front-end, and before clicking the button, they set a specific cookie, with a specific value that is "registered" to that user.  They also perform some magic behind the curtain that massages the virtual service that they are working on, so it clones the default DestinationRule, and adds a new header route to the VirtualService.  This will go along with an application gateway that is interposed between the front-end and the front-end services, which translates that specific cookie mentioned above to a header of the same name (or a translation).

With this configuration, the developer now has a pod that will only be sent requests that have that particular header set with a particular value, which only happen when that particular cookie is set in the front-end.  They can use the aforementioned debugger port and port-forward, without conflicting with the other developers and testers on the team.

This can be taken even further.  So far, with what we have here, this lets the developer debug the existing code in the cluster.  I want to give them the ability to test their uncommitted code within the cluster, without having to push to a pull request, and without disturbing any other developers or testers on the team.

This is where the "Telepresence" framework comes in.  If you haven't heard of this, this is a framework that works with k8s.  It basically lets you set up a local process with a proxy in the cluster, so that any request that goes to the pod in the cluster, actually goes to the local process.  It's cleaner to make this local process a docker container, but there are other possibilities.

With these capabilities in place, our feedback loop will shorten even more. We will have much stronger assurance that the code that actually gets merged and deployed has a better chance of working properly.

Again, we're still in the Istio prototype stage.  It seems like it will take forever to come to fruition, but in the meantime, I've been trying to find avenues to talk about these notions, so there may be some public experience to go from when we get there.  I'm somewhat concerned about that "magic behind the curtain" that I mentioned.  It's certainly straightforward to add routes to a VS, but for this to be a smooth process, it would be best if the addition (and removal) of those routes could be semi-automated, not to mention the cloning of the DestinationRule.

Hopefully this is something you could explore and get some experience with so that some of these automation ideas could be considered.

**Comment by meganokeefe** [comment]
Hi David, thanks for sharing this. I think that leveraging Istio and Telepresence for controlling a Java debugger on Kubernetes is a really interesting idea. 

I'd encourage you to check out the [Istio User Experience working group](https://github.com/istio/community/blob/master/WORKING-GROUPS.md) meeting, and the [Istio Discourse](https://discuss.istio.io/) forum, to share this idea with others and get feedback. As far as automating the VirtualService routes / DestinationRule creation, the [Istio Golang client library](https://github.com/istio/client-go) may be of interest. You could write a small Go agent running as a Kubernetes Job or Pod that takes care of those Istio resource tasks. (Unfortunately there isn't a Java client lib yet.) 

One other thought about the overall developer workflow you described -- it may be worth considering changing the underlying Kubernetes dev infrastructure here. Having multiple developers working on the same dev cluster and the same deployment introduces a risk of clobbering each other's changes (as you described). Perhaps you've already considered this, but you could instead create a namespace per developer -- in the dev cluster -- or [even give developers their own cluster](https://devspace.cloud/blog/2020/01/09/access-to-kubernetes-for-developers), cloud-hosted or local (eg. Minikube). This would mean that each developer would have their own dedicated deployment and debugger, perhaps avoiding the need for Istio here. There are also developer-facing tools for Kubernetes that could speed up development, including Cloud Code (IDE integration) and Skaffold (continously build + deploy containers). But I understand there are pros and cons to this (more expensive to give each developer their own cluster or namespace).  

I'm going to close this issue, but don't hesitate to reach back out.
